export var RECEIVE_NEWS_LIST = "RECEIVE_NEWS_LIST";
export var ENTER_TO_PROFILE_TRUE = "ENTER_TO_PROFILE_TRUE";
export var EXIT_THE_PROFILE ='EXIT_THE_PROFILE';
export var SHOW_LOADER = "SHOW_LOADER";
export var HIDE_LOADER = "HIDE_LOADER";